// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpdateHistory.Models;

namespace UpdateHistory.Migrations
{
    [DbContext(typeof(UpdateHistoryContext))]
    [Migration("20190205151210_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UpdateHistory.Models.Info", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Architecture");

                    b.Property<string>("Classification");

                    b.Property<string>("ICW");

                    b.Property<string>("KBID");

                    b.Property<string>("LastModified");

                    b.Property<string>("MSRCNumber");

                    b.Property<string>("MSRCSeverity");

                    b.Property<string>("SupportedLanguages");

                    b.Property<string>("SupportedProducts");

                    b.Property<DateTime>("TestDate");

                    b.Property<string>("TestResults");

                    b.Property<string>("Title");

                    b.Property<string>("UpdateStatus");

                    b.Property<string>("Server");

                    b.Property<string>("updateID");

                    b.HasKey("ID");

                    b.ToTable("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
